##
## Makefile for Makefile in /home/alex-odet/work/Test_SDL
## 
## Made by Alexandre Odet
## Login   <alex-odet@epitech.net>
## 
## Started on  Sat Mar  1 14:41:33 2014 Alexandre Odet
## Last update Sat Mar  1 14:44:10 2014 Alexandre Odet
##

NAME=	SDL_TEST

CC=	gcc

SRC=	*.c

T=	*~

RM=	rm -f

all:
	$(CC) -o $(NAME) $(SRC) -lSDL

clean:
	$(RM) $(T)

fclean:	clean
	$(RM) $(NAME)

re:	fclean all